### ISSUE TITLE
[FEAT] How to use the @Mention extension of tiptap v2 with ngx-tiptap? 

### ISSUE THREAD

**Issue by GitHubish** [sibiraj-s/ngx-tiptap#5]
I'm looking at how to use the [@Mention extension](https://www.tiptap.dev/examples/suggestions) from Tiptap v2 native extensions but I see that in their doc they have an explicit reference to VueRenderer (from Vuejs) and a reference to the Tippy library for popover. The dependency on Tippy.js is not a problem, but on the other hand I don't see well how to replace the VueJS part by the Angular equivalent. Any idea ? Thanks and very good work it's very cool ! I see a lot of things possible with this library.

**Comment by sibiraj-s** [comment]
Hi, You should be able to do this by using Dynamic components. Just few lines. I have some personal situation to attend once I am back I will add some easy to use API for the same. 

Ref: [Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader)

**Comment by GitHubish** [comment]
On my side I was looking to reimplement the equivalent of their [VueRenderer](https://github.com/ueberdosis/tiptap/blob/4fa75d842ede87631348783fd6dc8f8fc1afc2be/packages/vue-3/src/VueRenderer.ts) or [ReactRenderer](https://github.com/ueberdosis/tiptap/blob/4fa75d842ede87631348783fd6dc8f8fc1afc2be/packages/react/src/ReactRenderer.tsx). I'm trying to get inspired by what you did with the [NodeViewRenderer](https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/src/lib/NodeViewRenderer.ts) but I have to admit that I'm missing some knowledge. Maybe it's not the right solution but I took the logic of the Tiptap team.

**Comment by sibiraj-s** [comment]
Added `AngularRenderer`. So the rough implementation with mentions extensions will be like. 

```ts
new Editor({
  extensions: [
    Document,
    Paragraph,
    Text,
    Mention.configure({
      HTMLAttributes: {
        class: 'mention',
      },
      suggestion: {
        items: (query) => {
          return [
            'Lea Thompson',
            'Cyndi Lauper',
            'Tom Cruise',
            'Madonna',
            'Jerry Hall',
            'Joan Collins',
            'Winona Ryder',
            'Christina Applegate',
            'Alyssa Milano',
            'Molly Ringwald',
            'Ally Sheedy',
            'Debbie Harry',
            'Olivia Newton-John',
            'Elton John',
            'Michael J. Fox',
            'Axl Rose',
            'Emilio Estevez',
            'Ralph Macchio',
            'Rob Lowe',
            'Jennifer Grey',
            'Mickey Rourke',
            'John Cusack',
            'Matthew Broderick',
            'Justine Bateman',
            'Lisa Bonet',
          ]
            .filter((item) => item.toLowerCase().startsWith(query.toLowerCase()))
            .slice(0, 10);
        },
        render: () => {
          let renderer;
          let popup;

          return {
            onStart: (props) => {
              renderer = new AngularRenderer(MentionsComponent, injector);

              renderer.instance.props = props;

              popup = tippy('body', {
                getReferenceClientRect: props.clientRect,
                appendTo: () => document.body,
                content: renderer.dom,
                showOnCreate: true,
                interactive: true,
                trigger: 'manual',
                placement: 'bottom-start',
              });
            },
            onUpdate(props) {
              renderer.instance.props = props;

              popup[0].setProps({
                getReferenceClientRect: props.clientRect,
              });
            },
            onKeyDown(props) {
              return renderer.dom?.onKeyDown(props);
            },
            onExit() {
              popup[0].destroy();
              component.destroy();
            },
          };
        },
      },
    }),
  ],
  content: '',
});
```

Note: I didn't test this.

**Comment by sibiraj-s** [comment]
Fixed in v1.4.0

**Comment by GitHubish** [comment]
@sibiraj-s Thank you for this work !! It helped me to move forward. I have changed things a bit. But I still have a problem, with the current mechanics proposed by Tiptap  with the use of TippyJS, the detection of changes in the component `MentionsComponent` does not work even if I force it by using the method `markForCheck()`.  I tried in the component to update the content of TippyJS (like this `popover.setContent(this.elementRef.nativeElement)`) but same thing, it refreshes only when I press a key. So the list of proposals is still "lagging". Do you have an idea?

```
Mention.configure({
          HTMLAttributes: {
            class: 'mention',
          },
          suggestion: {
            render: () => {
              let component: AngularRenderer<MentionsComponent>;
              let popovers: Instance<Props>[];

              return {
                //items: [], => The get of items is done in the component because it queries an API
                onStart: (props) => {
                  component = new AngularRenderer(MentionsComponent, this.injector);
                  component.instance.setProps(props);

                  popovers = tippy('body', {
                    getReferenceClientRect: props.clientRect,
                    appendTo: () => document.body,
                    content: component.dom,
                    showOnCreate: true,
                    interactive: true,
                    trigger: 'manual',
                    placement: 'bottom-start',
                    hideOnClick: false
                  });

                  //NOTE: Set the TippyJs instance to component to eventually try to force the render once the results are loaded (get api)
                  component.instance.setPopover(popovers[0]);
                },
                onUpdate(props) {
                  component.instance.setProps(props);
                  popovers[0].setProps({
                    getReferenceClientRect: props.clientRect,
                  });
                },
                onKeyDown(props) {
                  //NOTE: I edited the proposed code that did not work. So I call directly a method of the component which treats the events
                  return component?.instance?.onKeyDown(props);
                },
                onExit() {
                  component.instance.ngOnDestroy();
                  popovers[0].destroy();
                  component.destroy();
                },
              };
            },
},
```

**Comment by sibiraj-s** [comment]
I made a working example of mentions few days back. https://stackblitz.com/edit/ngx-tiptap-mentions. Let me know if that helps.

**Comment by GitHubish** [comment]
This is indeed the result I got but by trying to make the list of items displayed dynamic depending on the return of an API makes the behavior I was describing this to say that the content of the list does not update. I implemented the logic directly in the MentionsList component. The suggestions extension of Tiptap can normally accept a promise instead of an array of values, their TS definition does not seem to allow this. 

Here is an example of my prototype in which I have this problem. Maybe the way I do it is clearly not the right way? I tried to force a refresh of the view after my call (simulated in the loadEntries() method) but it doesn't work.

[Example](https://stackblitz.com/edit/ngx-tiptap-mentions-ws4c5m?file=src%2Fapp%2Fmentions%2Fmentions.component.ts)

**Comment by sibiraj-s** [comment]
I understand that you are facing some issue with the async items. The issue is not related to this library. As much as I would like to help, but I don't have the energy to spend around this. I am most likely tested +ve waiting for results. 

Checkout https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh?hl=en&authuser=0

It should be able you find the issue.

**Comment by GitHubish** [comment]
Oh :(! I totally understand, I hope the results are negative. Take care of yourself! 
Thanks for the resource, I'll give it a try and see how it can help me. Thanks again for the exchange and for your time!

**Comment by Maximaximum** [comment]
@sibiraj-s would you mind updating https://stackblitz.com/edit/ngx-tiptap-mentions so that it uses compatible versions of angular core (currently v12) and angular cli (currently v11)?

Even though the stackblitz demo works online at https://stackblitz.com/edit/ngx-tiptap-mentions, it does not work locally on my machine due to multiple incompatibilities between package versions. I've tried to manually update angular locally, but the solution still has some compilation errors.

**Comment by sibiraj-s** [comment]
Sure. will do @Maximaximum

**Comment by sibiraj-s** [comment]
The examples are now updated with recent tiptap version.

**Comment by Maximaximum** [comment]
@sibiraj-s Thanks a lot! Will try it out now

**Comment by Maximaximum** [comment]
Looks like you still have outdated `devDependencies`: `@angular-devkit/build-angular`, `@angular/cli` and `@angular/compiler-cli` all point to v11.

I'm not sure why this works at stackblitz, probably due to some package caching mechanism. But it does not work locally. And trying to manually update these dependencies locally produces other errors.

**Comment by sibiraj-s** [comment]
Hi, My guess is that stackblitz entirely ignores the dependencies/devDependencies in the manifest and uses the dependencies found in the sidebar and own version of cli to run angular project. Or something else 🤷 

Can you fire up a new project using the cli and copy the files there and try?

**Comment by Maximaximum** [comment]
@sibiraj-s Indeed, by creating a new project via ng cli and copying the component files there (and making some additional changes), I was finally able to make it work locally. Thank you!
